# Generated by Django 4.0.3 on 2023-02-20 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='publisher',
        ),
        migrations.AlterField(
            model_name='book',
            name='publishedDate',
            field=models.TextField(),
        ),
    ]
